name: Publish TechDocs Site

on:
  push:
    branches: [main]
    # You can even set it to run only when TechDocs related files are updated.
    # paths:
    #   - "docs/**"
    #   - "mkdocs.yml"

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest

    # The following secrets are required in your CI environment for publishing files to Azure Blob Storage.
    # e.g. You can use GitHub Organization secrets to set them for all existing and new repositories.
    # See https://backstage.io/docs/features/techdocs/configuring-ci-cd for other providers configuration.
    env:
      
      TECHDOCS_BLOB_STORAGE_NAME: ${{ secrets.TECHDOCS_BLOB_STORAGE_NAME }}
      AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
      AZURE_ACCOUNT_KEY: ${{ secrets.AZURE_ACCOUNT_KEY }}
      
      ENTITY_NAMESPACE: 'default'
      ENTITY_KIND: 'Component'
      ENTITY_NAME: 'test1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type azureBlobStorage --azureAccountName $AZURE_ACCOUNT_NAME --azureAccountKey $AZURE_ACCOUNT_KEY --storage-name $TECHDOCS_BLOB_STORAGE_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
